import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

import { headers } from "next/headers";

const poppins = Poppins({
  weight: ["500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersData = await headers();
  const pathname = headersData.get("x-next-url") || "/";
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className} font-[700] max-w-screen `}
      >
        <Navbar />
        {children}
        {pathname !== "/" && <Footer />}
      </body>
    </html>
  );
}
